### PR TITLE
Project # 1: Positioning and floating elements

### PR DESCRIPTION
**Pull request by FdI96**
The project pull request will merge the branch to the main repository branch.

The feature branch shows the content that was built with HTML and CSS and has passed the Linters testing phase. 

The main branch only contains the commit for the linters workflow, where the feature branch contains all commits for the project history. 

The commits cover the tasks so far in the learning path, such as utilizing Grid, Flexbox, and Float to develop the base for the web page. 

Milestones covered:
Milestone 1 - project setup & assets 
Milestone 2 - website skeleton 
Milestone 3 - markup & simple styling
Milestone 4 - first complete version
Milestone 5 - final touches 
Milestone 6 - deployment & documentation

Do not hesitate to make suggestions, this project is open for improvements.

### CODE REVIEW

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @FdI96 and @JohnHernandez-code, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏  I appreciate your hard work in replicating nytimes.com.   Kindly fix the following issues.

[REQUIRED]

- [ ] Use similar fonts and font style as the original page.
- [ ] Fix the  Editor's picks style.
aside article

- [ ] Fix the bottom part of the page, compare your clone with the original page.
original bottom

- [ ] The "The Theory of Inflation" section should align center.
- [ ] Add the bottom navigation 
- [ ] Add the Most Popular section 
- [ ] Add the More section 
- [ ] Add the footer

[OPTIONAL] 

- [ ] Add a fixed footer (it sticks to the bottom part of the screen)
sticky footer

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [x] Remove horizontal scrolling from your webpage. 

- [x] The navbar should be sticky. This is how it is present on the original page. 

- [x] Images from **The Theory of Inflation** is not rendering. I think you don't have those please work on them. 

- [x] `More in Space and Astronomy` is missing an image. please work on it. 

- [x] The NYT logo should be a link in both the footer and navbar. Please work on it. 

- [ ] MIT link is broken. 

- [ ] Add a live link to your project. 

**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by FdI96** [comment]
> # Request changes 😳
> I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project
> 
> _It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
> 
> This is a great opportunity to learn. Microverse is here to help you.
> 
> **Please have a look at the suggestions to get more understanding.**
> 
> * [x]  Remove horizontal scrolling from your webpage.
> * [x]  The navbar should be sticky. This is how it is present on the original page.
> * [x]  Images from **The Theory of Inflation** is not rendering. I think you don't have those please work on them.
> * [x]  `More in Space and Astronomy` is missing an image. please work on it.
> * [x]  The NYT logo should be a link in both the footer and navbar. Please work on it.
> * [ ]  MIT link is broken.
> * [ ]  Add a live link to your project.
> 
> **Please make the changes and request a re-review for the given project**
> 
> If you get stuck somewhere, don't hesitate to reach out or schedule s 1:1 meeting with a Full-time TSE.
> 
> Stay safe and give me a smile 😇
> 
> ### Happy Coding
> **Regards, Arslan Bisharat slack: arslanbisharat**

Hey There! Where should I publish my live link to my project? Does it go in the README.md file? And actually, I can enter in the MIT link. I just need to fix those 2 things the rest's done. Thank you so much for your patient. 😄

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
Hi Team ! 👋 👋 👋 

### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Recommended**
- [x] The image in the "Theory of Inflation" still is not rendering. Please fix this.

**Optional**

- [ ] Fix the navbar and the footer to look as similar as possible to the actual site's. 


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi Team! 👋 👋 👋 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada: 💯 

### You may merge, good luck with your next projects! :rocket:
### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
